name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: |
          echo "CC=$(brew --prefix gcc@13)/bin/gcc-13" >> "${GITHUB_ENV}"
          echo "FC=$(brew --prefix gcc@13)/bin/gfortran-13" >> "${GITHUB_ENV}"
          echo "LIBRARY_PATH=$(brew --prefix gcc@13)/lib/gcc/13" >> "${GITHUB_ENV}"
      - run: rustup toolchain install stable --profile=minimal --component clippy --component rustfmt
      - run: cargo clippy -- -D warnings
      - run: cargo fmt --all -- --check

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: |
          echo "CC=$(brew --prefix gcc@13)/bin/gcc-13" >> "${GITHUB_ENV}"
          echo "FC=$(brew --prefix gcc@13)/bin/gfortran-13" >> "${GITHUB_ENV}"
          echo "LIBRARY_PATH=$(brew --prefix gcc@13)/lib/gcc/13" >> "${GITHUB_ENV}"
      - run: rustup toolchain install stable --profile=minimal
      - run: cargo test

  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: rustup toolchain install stable --profile=minimal
      - run: cargo test
